// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountEntry: typeof import('./src/components/AccountEntry.vue')['default']
    AccountsTable: typeof import('./src/components/AccountsTable.vue')['default']
    AddAccountModal: typeof import('./src/components/AddAccountModal.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    GoogleAutocomplete: typeof import('./src/components/GoogleAutocomplete.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    MyProfile: typeof import('./src/components/MyProfile.vue')['default']
    MyTable: typeof import('./src/components/MyTable.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    Paypal: typeof import('./src/components/Paypal.vue')['default']
    QuoteCard: typeof import('./src/components/QuoteCard.vue')['default']
    QuoteForm: typeof import('./src/components/QuoteForm.vue')['default']
    QuoteTable: typeof import('./src/components/QuoteTable.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
  }
}

export { }
